### ISSUE TITLE
希望能提供命令行操作

### ISSUE THREAD

**Issue by 1143910315** [syj2010syj/w3x2lni#3]
希望有隐藏主程序和控制台，完全的命令行操作，这可以减少超多步骤。
如果有，麻烦透露下吧。

**Comment by actboy168** [comment]
自己准备一个lua.exe放到w3x2lni目录下,然后lua.exe -script/main.lua -backend 地图路径

**Comment by 1143910315** [comment]
我一定是用了假lua.exe

**Comment by LazyKnightX** [comment]
作为一个补充，下载lua.exe的地址：http://luabinaries.sourceforge.net/download.html

**Comment by sumneko** [comment]
请不要随意回复已经关闭的issue @LazyKnightX
